baseURL: 'https://karanrn.me/'
languageCode: 'en-us'
title: 'Karan Nadagoudar'
theme: "hugo-book"

# Book configuration
disablePathToLower: true
enableGitInfo: false

copyright: "Copright %copy; 2023, Karan Nadagoudar"

params:
  BookTheme: "light"
  BookToC: false
  BookRepo: https://github.com/karanrn/karanrn.me
  BookSearch: true

menu:
  after:
  - name: movies
    url: https://letterboxd.com/karan4080/
    weight: 110
